name: CD with AWS EC2

on: 
  workflow_run:
    workflows: [CI with Docker Compose]
    types: 
      - completed
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_HOST : ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY : ${{ secrets.EC2_SSH_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      UPLOAD_DIR: ${{ secrets.UPLOAD_DIR }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/Project-management-app/"
 
      - name: Deploy app on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, AWS_REGION, S3_BUCKET_NAME, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, DATABASE_URL, UPLOAD_DIR, SECRET_KEY, ALGORITHM, ACCESS_TOKEN_EXPIRE_MINUTES
          script: |
            cd /home/ubuntu/Project-management-app/
            # Crear archivo .env dentro de EC2
            mkdir -p .env
            cat <<EOF > .env/.env
            POSTGRES_USER=${POSTGRES_USER}
            POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            POSTGRES_DB=${POSTGRES_DB}
            AWS_REGION=${AWS_REGION}
            S3_BUCKET_NAME=${S3_BUCKET_NAME}
            AWS_ACCESS_KEY_ID = ${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY = ${AWS_SECRET_ACCESS_KEY}
            DATABASE_URL=${DATABASE_URL}
            UPLOAD_DIR=${UPLOAD_DIR}
            SECRET_KEY=${SECRET_KEY}
            ALGORITHM=${ALGORITHM}
            ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
            EOF
        
            # Build and start services
            sudo docker compose -f docker-compose.yml --env-file .env/.env up -d --build

            # Wait for Postgres to be ready
            until sudo docker exec database-PostgreSQL pg_isready -U admin; do
              echo "Waiting for Postgres..."
              sleep 5
            done



