name: CI with Docker Compose

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      EC2_HOST : ${{ secrets.EC2_HOST }}
      EC2_SSH_KEY : ${{ secrets.EC2_SSH_KEY }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      UPLOAD_DIR: ${{ secrets.UPLOAD_DIR }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      ALGORITHM: ${{ secrets.ALGORITHM }}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Create .env file
        run: |
          mkdir -p .env
          echo "POSTGRES_USER=$POSTGRES_USER" >> .env/.env
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env/.env
          echo "POSTGRES_DB=$POSTGRES_DB" >> .env/.env
          echo AWS_REGION = $AWS_REGION >> .env/.env
          echo S3_BUCKET_NAME = $S3_BUCKET_NAME >> .env/.env
          echo AWS_ACCESS_KEY_ID = $AWS_ACCESS_KEY_ID >> .env/.env
          echo AWS_SECRET_ACCESS_KEY = $AWS_SECRET_ACCESS_KEY >> .env/.env
          echo EC2_HOST = $EC2_HOST >> .env/.env
          echo EC2_SSH_KEY = $EC2_SSH_KEY >> .env/.env
          echo DATABASE_URL = $DATABASE_URL >> .env/.env
          echo UPLOAD_DIR = $UPLOAD_DIR >> .env/.env
          echo SECRET_KEY = $SECRET_KEY >> .env/.env
          echo ALGORITHM = $ALGORITHM >> .env/.env
          echo ACCESS_TOKEN_EXPIRE_MINUTES = $ACCESS_TOKEN_EXPIRE_MINUTES >> .env/.env
     
      - name: Debug secrets
        run: |
          echo "DATABASE_URL=$DATABASE_URL"
          echo "AWS_REGION=$AWS_REGION"
          echo "POSTGRES_USER=$POSTGRES_USER"
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD"
          echo "POSTGRES_DB=$POSTGRES_DB"
          echo "SECRET_KEY=$SECRET_KEY"
          echo "ALGORITHM=$ALGORITHM"
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES"
          echo "UPLOAD_DIR=$UPLOAD_DIR"
          echo "S3_BUCKET_NAME=$S3_BUCKET_NAME"
          echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
          echo "EC2_HOST=$EC2_HOST"
          echo "EC2_SSH_KEY=$EC2_SSH_KEY"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start services
        run: |
          docker compose -f docker-compose.yml up -d --build

      - name: Wait for Postgres to be ready
        run: |
          until docker exec database-PostgreSQL pg_isready -U admin; do
            echo "Waiting for Postgres..."
            sleep 5
          done
 
      - name: Run tests inside container
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml up --build --exit-code-from test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/coverage.xml
          fail_ci_if_error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull <account_id>.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/myapp:latest
            docker-compose -f docker-compose.yml up -d --build

      - name: Shut down services
        if: always()
        run: docker compose -f docker-compose.yml down

